# Common Labels
labels:
  app: "trai-gateway"
  group: "ispirit"
namespace: ispirit

# Container Configs
image:
  repository: "trai-gateway"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/trai-gateway/actuator/health"
  readinessProbePath: "/trai-gateway/actuator/health"
heap: "-Xmx256M -Xms256M"
java-args: "-Dspring.profiles.active=monitoring"
memory_limits: 512Mi
resources: |
  requests:
    memory: {{ .Values.memory_limits | quote }}
  limits:
    memory: {{ .Values.memory_limits | quote }}

# Additional Container Envs
env: |
  - name: APP_TIMEZONE
    value: "Asia/Kolkata"     
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /trai-gateway    
  - name: SERVER_PORT
    value: "8080" 
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}  
  - name: TELCO_CONFIG_PATH
    value: "/etc/ispirit/telcos-secret.json"          
  - name: CLIENT_SSL_CERT_PATH
    value: "/etc/certs/cert.pem" 
  - name: CLIENT_SSL_CA_PATH
    value: "/etc/certs/ca.pem" 
  - name: CLIENT_SSL_PRIVATE_KEY_PATH
    value: "/etc/certs/private-key.pem"             

extraVolumes: |
  - name: crypto-keys
    secret:
      secretName: {{ index .Values "global" "moca-domain" }}-tls-certs
      defaultMode: 288 # = mode 0440
  - name: ca-certs
    configMap:
      name: ca-certs
  - name: telcos-secret
    secret:
      secretName: ispirit-ecurfew
      defaultMode: 288 # = mode 0440      

extraVolumeMounts: |
  - mountPath: /etc/certs/cert.pem
    name: crypto-keys
    subPath: tls.crt
  - mountPath: /etc/certs/private-key.pem
    name: crypto-keys
    subPath: tls.key
  - name: ca-certs
    mountPath: /etc/certs/ca.pem   
    subPath: ca.pem    
  - mountPath: /etc/ispirit/telcos-secret.json
    name: telcos-secret
    subPath: telcos-secret.json    
