labels:
  app: "postgres"
  group: "db"
namespace: egov

image:
  repository: "docker.io/postgres"
  tag: "9.6"
replicas: "1"
httpPort: 5432

resources: |
  requests:
    cpu: 100m
    memory: 356Mi

tracing-enabled: false

env: |
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name:  POSTGRES_USER
    valueFrom: 
      secretKeyRef: 
        name: db
        key: username
  - name: POSTGRES_DB
    value: {{ default "" .Values.postgresDatabase | quote }}

postgresDatabase: upyog_sandbox_db

persistence:
  enabled: true
  aws:
    volumeId: "vol-00c9fa54fff988b0c"
  storageClassName: gp2
  accessMode: ReadWriteOnce
  dataDirSize: 300Gi 
  volumeMode: Filesystem

extraVolumeMounts: |
  - mountPath: /var/lib/postgresql/data
    name: postgres-data
    subPath: html
extraVolumes: |
  - name: postgres-data
    persistentVolumeClaim:
      claimName: postgres-data
