apiVersion: v2
name: nginx-ingress
description: An nginx Ingress controller that uses ConfigMap to store the nginx configuration.
type: application
keywords:
  - ingress
  - nginx
sources:
  - https://github.com/kubernetes/ingress-nginx
engine: gotpl
kubeVersion: ">=1.10.0-0"
version: 1.0.0