{{- $serviceName := include "nginx-ingress.name" . -}}
{{- if or .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "nginx-ingress.name" . }}
  name: {{ template "nginx-ingress.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}  
{{- end -}}