# Common Labels
labels:
  app: "epasszuul"
  group: "gateway"

serviceAccount: epasszuul
namespace: ispirit  

# Init Containers Configs
initContainers: 
  extraInitContainers: |
    - name: "zuul-kubernetes-discovery"
      image: "{{ .Values.global.containerRegistry }}/zuul-kubernetes-discovery:2-master-91c9795"      
      env: 
      - name: "OUTPUT_FILE_PATH"
        value: "/etc/zuul/routes.properties" 
      - name: "NAMESPACE"
        value: "ispirit"         
      volumeMounts:
      - name: zuul-routes
        mountPath: /etc/zuul

extraVolumes: |
  - name: zuul-routes
    emptyDir: {}  

extraVolumeMounts: |     
  - name: zuul-routes
    mountPath: "/etc/zuul"

# Container Configs
image:
  repository: "epasszuul"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/health"
  readinessProbePath: "/health"
custom-filter-property: "false"
posthook-config: ""
prehook-config: ""
heap: "-Xmx192m -Xms192m"
tracing-enabled: true
server-tomcat-max-threads: "350"
server-tomcat-max-connections: "1500"
java-args: ""
egov-open-endpoints-whitelist: "/ecurfew/requestOTP,/ecurfew/verifyOTP,/ecurfew/resendOTP,/ecurfew/fetchStateList,/ecurfew/signin,/ecurfew/addOrganization,/ecurfew/createAccount,/ecurfew/fetchStateList,/ecurfew/verifyToken,/ecurfew/createOrder,/ecurfew/upload"  
egov-mixed-mode-endpoints-whitelist: ""
eventlog-enabled: "false"
eventlog-topic: "zuul-event-log"
eventlog-urls-whitelist: ""

# Additional Container Envs
env: |
  - name: URL_LISTS
    value: ""
  - name: CUSTOM_FILTER_PROPERTY
    value: {{ index .Values "custom-filter-property" | quote }}
  - name: CUSTOM_FILTER_POSTHOOKS
    value: "false"
  - name: CUSTOM_FILTER_PREHOOKS
    value: "false"
  - name: URL_POSTHOOK_LISTS
    value: {{ index .Values "posthook-config" | quote }}
  - name: URL_PREHOOK_LISTS        
    value: {{ index .Values "prehook-config" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: epass-api-gateway
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: EGOV_CUSTOM_ASYNC_FILTER_TOPIC
    value: res-custom-filter
  - name: EGOV_OPEN_ENDPOINTS_WHITELIST
    value: {{ index .Values "egov-open-endpoints-whitelist" | quote }}  
  - name: EGOV_MIXED_MODE_ENDPOINTS_WHITELIST
    value: {{ index .Values "egov-mixed-mode-endpoints-whitelist" | quote }}    
  - name: EVENTLOG_ENABLED
    value: {{ index .Values "eventlog-enabled" | quote }}   
  - name: EVENTLOG_TOPIC
    value: {{ index .Values "eventlog-topic" | quote }}   
  - name: EVENTLOG_URLS_WHITELIST
    value: {{ index .Values "eventlog-whitelist" | quote }}   
  - name: EGOV_AUTH_SERVICE_HOST
    value: "http://ecurfew:8080/"
  - name: EGOV_AUTH_SERVICE_URI
    value: "ecurfew/session/_search?authToken="
  - name: ZUUL_HOST_CONNECT_TIMEOUT_MILLIS
    value: "20000"
  - name: ZUUL_HOST_SOCKET_TIMEOUT_MILLIS
    value: "60000"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true"
  {{- end }}
  - name: SECURITY_BASIC_ENABLED
    value: "false"
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: EGOV_STATELEVEL_TENANT
    value: "in"
  - name: ZUUL_ROUTES_FILEPATH
    value: "file:/etc/zuul/routes.properties"   
