# Common Labels
labels:
  app: "storybook"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "storybook"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "storybook"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/storybook/"
  readinessProbePath: "/storybook/"

namespace: egov    

